main: fr.martinfimbel.minecraft_cutclean.CutcleanPlugin
name: minecraft-cutclean
version: 1.0-SNAPSHOT
api-version: 1.13
depend: [minecraft-game-plateform]

description:
commands:
  cutclean:
    description: cutclean configuration command
    permission: cutclean.permission